exclude: 'docs|node_modules|migrations|.git|.tox|package.json|.mypy_cache|.pytest_cache|.vscode|css|app/static|CHANGELOG.md'
default_stages: [commit]
fail_fast: true

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml

  - repo: https://github.com/psf/black
    rev: 24.2.0
    hooks:
      - id: black
        args: ['-l', '99']

  - repo: https://github.com/timothycrosley/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: ['--profile', 'black']

  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        args: ['--config=backend/setup.cfg']
        additional_dependencies: [flake8-isort]
