# Generated by Django 5.0.3 on 2024-03-08 09:15

import django.db.models.deletion
import phonenumber_field.modelfields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to='images/')),
                ('description', models.TextField()),
                ('brand', models.CharField(max_length=256)),
                ('bike_type', models.CharField(max_length=256)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BikeOwner',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('second_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('contact', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('id_photo', models.ImageField(upload_to='images')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BikeOwnerBikeAllocation',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('bike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.bike')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.bikeowner')),
            ],
        ),
        migrations.AddField(
            model_name='bikeowner',
            name='bikes',
            field=models.ManyToManyField(related_name='my_bikes', through='base.BikeOwnerBikeAllocation', to='base.bike'),
        ),
        migrations.CreateModel(
            name='BikeShop',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('shop_location', models.CharField(max_length=100)),
                ('attendant', models.CharField(max_length=256)),
                ('contact', models.CharField(max_length=256)),
                ('bikeowner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.bikeowner')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BikeShopAllocation',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('bike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.bike')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.bikeshop')),
            ],
        ),
        migrations.AddField(
            model_name='bikeshop',
            name='bikes',
            field=models.ManyToManyField(related_name='shop_bikes', through='base.BikeShopAllocation', to='base.bike'),
        ),
        migrations.CreateModel(
            name='CustomerBikeAllocation',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('bike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.bike')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.customer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='bikeownerbikeallocation',
            constraint=models.UniqueConstraint(fields=('bike', 'owner'), name='unique_owner_bike_pair'),
        ),
        migrations.AddConstraint(
            model_name='bikeshopallocation',
            constraint=models.UniqueConstraint(fields=('bike', 'shop'), name='unique_shop_bike_pair'),
        ),
    ]
